"""empty message

Revision ID: 7425d859625e
Revises: 424ed66a7ba1
Create Date: 2024-05-19 20:53:06.388491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7425d859625e'
down_revision = '424ed66a7ba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=5), nullable=True, default="USER"))
        batch_op.create_index(batch_op.f('ix_usuarios_tipo'), ['tipo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_tipo'))
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
