"""empty message

Revision ID: f522e315da63
Revises: 7425d859625e
Create Date: 2024-05-19 21:54:31.717113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f522e315da63'
down_revision = '7425d859625e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.drop_index('ix_usuarios_tipo')
        batch_op.create_index(batch_op.f('ix_usuarios_tipo'), ['tipo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_tipo'))
        batch_op.create_index('ix_usuarios_tipo', ['tipo'], unique=1)
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)

    # ### end Alembic commands ###
